# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XuqXikD7NF0TofPUw7Hav-X3M84Oawao
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

muons= pd.read_csv('https://goo.gl/sp8gYx')
muons.head()

muons['Masainvariante']=(((muons.E1+muons.E2)**2)-(((muons.px1+muons.px2)**2)+((muons.py1+muons.py2)**2)+((muons.pz1+muons.pz2)**2)))**.5
muons.head()

fig= plt.figure(figsize=(15,10))
plt.hist(muons.Masainvariante, 300, range=(0,150))
plt.xlabel('Masa invariante (GeV/$c^2$)', fontsize = 15)
plt.ylabel('Número de eventos \n', fontsize = 15)
plt.title('Distribución media de eventos con dos muones \n', fontsize = 15)

plt.show()

bump= muons[(muons.Masainvariante >= 80) & (muons.Masainvariante <= 100)]

fig = plt.figure(figsize=(15, 10))

plt.hist(bump.Masainvariante, 300, range = (80,100))

plt.xlabel('Masa invariante (GeV/$c^2$)', fontsize = 15)
plt.ylabel('Número de eventos \n', fontsize = 15)
plt.title('Distribución media de eventpos con dos muones \n', fontsize = 15)

plt.show()